# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('red', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('yellow', models.IntegerField()),
                ('green', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('player', models.ManyToManyField(to='app.Players')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='team',
            field=models.ManyToManyField(to='app.Teams'),
        ),
    ]
