# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='num_of_member',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='players',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
